# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f34ae73c0851ae64c751165e991609c280b67f3f4cecea83b2f2957f86e3744bb10eea66a12806c3494798a65215756303de473e215e32b010971d7125c04f2

test:
  secret_key_base: 11468e206cf53d3a29749db13e03eb3d613ef7f8b9831496781abc3eaff41e5b3ac7f834f3654e3a0811b247a6e9a751fe11650623407acea154bc179decc3e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
