aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
s3:
  public:
    bucket: <%= ENV['S3_PUBLIC_BUCKET_NAME'] %>
  private:
    bucket: <%= ENV['S3_PRIVATE_BUCKET_NAME'] %>
  common:
    article_image_path: ':class/images/:id/:filename/:style'
    article_embedded_image_path: 'article/embedded_images/:id/:filename/:style'
