require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ArticleImagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ArticleImage. As you add validations to ArticleImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArticleImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ArticleImage" do
        expect {
          post :create, {:article_image => valid_attributes}, valid_session
        }.to change(ArticleImage, :count).by(1)
      end

      it "assigns a newly created article_image as @article_image" do
        post :create, {:article_image => valid_attributes}, valid_session
        expect(assigns(:article_image)).to be_a(ArticleImage)
        expect(assigns(:article_image)).to be_persisted
      end

      it "redirects to the created article_image" do
        post :create, {:article_image => valid_attributes}, valid_session
        expect(response).to redirect_to(ArticleImage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved article_image as @article_image" do
        post :create, {:article_image => invalid_attributes}, valid_session
        expect(assigns(:article_image)).to be_a_new(ArticleImage)
      end

      it "re-renders the 'new' template" do
        post :create, {:article_image => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested article_image" do
      article_image = ArticleImage.create! valid_attributes
      expect {
        delete :destroy, {:id => article_image.to_param}, valid_session
      }.to change(ArticleImage, :count).by(-1)
    end

    it "redirects to the article_images list" do
      article_image = ArticleImage.create! valid_attributes
      delete :destroy, {:id => article_image.to_param}, valid_session
      expect(response).to redirect_to(article_images_url)
    end
  end

end
